### ISSUE TITLE
Erfassen ob man Material XY verleihen möchte

### ISSUE THREAD

**Issue by pemko123** [cevi/onlinemat#30]
Es gibt bei uns Material das wir nie verleihen wollen da wir wissen wollen wie damit umgegangen wird. Dies betrifft vorallem sicherheitsrelevantes wie:

- Seile
- Karabiner
- Gstältli etc.

Eventuell wäre es sinnvoll auf dem Material ein Boolean einzubauen zum sagen ob es externe mieten können?

**Comment by pemko123** [comment]
Heute hat ein Leiter viel Material erfasst. Leider steht jetzt bi allen das sie nur intern ausgeliehen werden dürfen, da der Default auf TRUE ist.

Wäre es nicht sinvoller diesen auf FALSE zu haben?

Was denkt ihr? @jan-preisig @Leo1212

**Comment by jan-preisig** [comment]
Von mir aus kann man den default gut auf false nehmen. Bei uns ist sicher auch die Mehrheit des Materials extern auch ausleihbar. @Leo1212 was denkst du?

**Comment by Leo1212** [comment]
@jan-preisig  & @pemko123 
Gute Frage. Ehrlich gesagt, glaube ich, dass es sehr Abteilungs abhänig ist, was man verleihen möchte. 
Ich kann mir gut vorstellen, dass gewisse Abteilungen nur 1-2 Sachen ausleihen lassen wollen. Z.B. Fallbalken oder so.
Und andere Abteilungen auch Kochtöpfe Blachen etc ausleihen ausleihen wollen.

Ich bin offen für beide Lösungen. Evtl wäre eine Lösung die Default Einstellung pro Abteilung zu speichern. Also in den Settings der Abteilung ein neues Flag: `defaultOnlyLendInternal` oder so.

**Comment by jan-preisig** [comment]
Ja das mit der Einstellung finde ich eine gute Idee,aich denke sowieso, dass immer mehr Abteilungseinstellungen dazu kommen werden. Hab auch schon gedacht, dass es nice wäre Start und Endzeit der Cevinachmittage Konfigurierbar zu machen

**Comment by Leo1212** [comment]
Gute Idee @jan-preisig

**Comment by pemko123** [comment]
Wäre gut der Standard auf der Abteilung...
