### ISSUE TITLE
Default Abteilung

### ISSUE THREAD

**Issue by pemko123** [cevi/onlinemat#42]
Ich denke es wäre super wenn man seine Abteilung definieren kann und diese dann automatisch geöffnet wird wenn man auf Abteilung klickt 

Die Liste mit allen Abteilungen bräcuhte es ja nur am Anfang

**Comment by jan-preisig** [comment]
@Leo1212 
Kann man hierzu user.type.ts ein neues feld mit defaultAbteilung hinzufügen?
Und wie kann ich auf der AbteilungDetails komponente auf die id des aktuellen users zugreifen?
Muss ich um die defaultAbteilung auf dem user zu speichern eine neue UserUtil klasse machen? Die gibt es so wie ich das sehe noch nicht.

**Comment by Leo1212** [comment]
@jan-preisig 
Ja, das Feld kannst du gerne im type hinzufügen. 
Ich würde allgemein gerne die Profilseite (src/views/profile/profile.tsx) überarbeiten. 
Das wäre dann perfekt, um dort seine Abteilung zu bearbeiten und auch den Rest wie Name, Email etc...

UserUtil Klasse klingt gut.
